name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install & build
        run: |
          yarn install
          yarn build
      - name: lint
        run: |
          yarn lint
      - name: typecheck
        run: |
          yarn typecheck
      - name: unittest
        run: |
          yarn test:unittest
      - name: e2e
        run: |
          yarn test:e2e
